"""Create all database tables

Revision ID: a83a9bafc4b0
Revises: 
Create Date: 2025-12-21 00:10:33.081946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83a9bafc4b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='projectstatus'), nullable=False, comment='项目状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_alternatives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='方案名称'),
    sa.Column('design_vector', sa.JSON(), nullable=False, comment='设计变量值向量'),
    sa.Column('generation_method', sa.String(length=50), nullable=True, comment='生成方法（如：full_factorial, orthogonal）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='设计方案表'
    )
    op.create_index('idx_design_alt_project', 'design_alternatives', ['project_id'], unique=False)
    op.create_table('design_variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='变量名称'),
    sa.Column('variable_type', sa.Enum('CONTINUOUS', 'DISCRETE', 'CATEGORICAL', name='variabletype'), nullable=False, comment='变量类型'),
    sa.Column('range_min', sa.Float(), nullable=True, comment='最小值（连续变量）'),
    sa.Column('range_max', sa.Float(), nullable=True, comment='最大值（连续变量）'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表（离散/分类变量）'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('description', sa.Text(), nullable=True, comment='变量描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='设计变量表'
    )
    op.create_table('mcdm_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('method', sa.String(length=50), nullable=True, comment='MCDM方法（如：TOPSIS, AHP, SAW）'),
    sa.Column('weights', sa.JSON(), nullable=True, comment='属性权重'),
    sa.Column('rankings', sa.JSON(), nullable=True, comment='方案排名结果'),
    sa.Column('scores', sa.JSON(), nullable=True, comment='综合得分'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='多准则决策分析表'
    )
    op.create_index('idx_mcdm_project', 'mcdm_analyses', ['project_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('key_objectives', sa.JSON(), nullable=True, comment='关键目标列表'),
    sa.Column('value_proposition', sa.Text(), nullable=True, comment='价值主张'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('n_squared_diagrams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='图表名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='图表描述'),
    sa.Column('diagram_metadata', sa.JSON(), nullable=True, comment='图表元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('pareto_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('pareto_front', sa.JSON(), nullable=True, comment='帕累托前沿设计方案IDs'),
    sa.Column('dominated_solutions', sa.JSON(), nullable=True, comment='被支配的方案IDs'),
    sa.Column('objective_values', sa.JSON(), nullable=True, comment='目标值数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='帕累托分析表'
    )
    op.create_index('idx_pareto_project', 'pareto_analyses', ['project_id'], unique=False)
    op.create_table('project_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('current_phase', sa.String(length=20), nullable=True, comment='当前阶段'),
    sa.Column('current_step', sa.Integer(), nullable=True, comment='当前步骤'),
    sa.Column('step_statuses', sa.JSON(), nullable=True, comment='各步骤状态'),
    sa.Column('last_accessed', sa.DateTime(), nullable=True, comment='最后访问时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('sensitivity_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('analysis_type', sa.String(length=50), nullable=True, comment='分析类型（如：local, global）'),
    sa.Column('variable_name', sa.String(length=255), nullable=True, comment='分析的变量名'),
    sa.Column('results', sa.JSON(), nullable=True, comment='分析结果数据'),
    sa.Column('tornado_data', sa.JSON(), nullable=True, comment='龙卷风图数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='敏感性分析表'
    )
    op.create_index('idx_sensitivity_project', 'sensitivity_analyses', ['project_id'], unique=False)
    op.create_table('user_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模型名称'),
    sa.Column('model_type', sa.Enum('PERFORMANCE', 'COST', 'UTILITY', name='modeltype'), nullable=False, comment='模型类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('formula', sa.Text(), nullable=True, comment='模型公式'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='模型参数'),
    sa.Column('code', sa.Text(), nullable=True, comment='Python代码'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户定义模型表'
    )
    op.create_table('value_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='属性名称'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('ideal_value', sa.Float(), nullable=True, comment='理想值'),
    sa.Column('worst_value', sa.Float(), nullable=True, comment='最差值'),
    sa.Column('optimization_direction', sa.Enum('MAXIMIZE', 'MINIMIZE', name='optimizationdirection'), nullable=True, comment='优化方向'),
    sa.Column('weight', sa.Float(), nullable=True, comment='权重'),
    sa.Column('definition', sa.Text(), nullable=True, comment='属性定义'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='价值属性表'
    )
    op.create_table('dvm_matrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目ID'),
    sa.Column('design_variable_id', sa.Integer(), nullable=False, comment='设计变量ID'),
    sa.Column('value_attribute_id', sa.Integer(), nullable=False, comment='价值属性ID'),
    sa.Column('influence_score', sa.Integer(), nullable=True, comment='影响分数（0/1/3/9）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['design_variable_id'], ['design_variables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_attribute_id'], ['value_attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_variable_id', 'value_attribute_id', name='uq_dvm_variable_attribute'),
    comment='DVM矩阵表'
    )
    op.create_index('idx_dvm_attribute', 'dvm_matrix', ['value_attribute_id'], unique=False)
    op.create_index('idx_dvm_project', 'dvm_matrix', ['project_id'], unique=False)
    op.create_index('idx_dvm_variable', 'dvm_matrix', ['design_variable_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='所属模型ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本描述'),
    sa.Column('code', sa.Text(), nullable=False, comment='代码快照'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否为活动版本'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['model_id'], ['user_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型版本表'
    )
    op.create_index('idx_model_version', 'model_versions', ['model_id', 'version'], unique=False)
    op.create_table('n_squared_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('diagram_id', sa.Integer(), nullable=False, comment='所属图表ID'),
    sa.Column('node_id', sa.String(length=50), nullable=False, comment='节点标识符'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='节点名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='节点描述'),
    sa.Column('position', sa.Integer(), nullable=True, comment='节点位置索引'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['diagram_id'], ['n_squared_diagrams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='N-squared节点表'
    )
    op.create_index('idx_nsq_node_diagram', 'n_squared_nodes', ['diagram_id'], unique=False)
    op.create_index('idx_nsq_node_id', 'n_squared_nodes', ['node_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('design_alternative_id', sa.Integer(), nullable=False, comment='所属设计方案ID'),
    sa.Column('performance_metrics', sa.JSON(), nullable=True, comment='性能指标值'),
    sa.Column('cost_metrics', sa.JSON(), nullable=True, comment='成本指标值'),
    sa.Column('utility_score', sa.Float(), nullable=True, comment='效用分数'),
    sa.Column('normalized_metrics', sa.JSON(), nullable=True, comment='归一化指标'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['design_alternative_id'], ['design_alternatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='仿真结果表'
    )
    op.create_index('idx_sim_result_design', 'simulation_results', ['design_alternative_id'], unique=False)
    op.create_table('n_squared_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('diagram_id', sa.Integer(), nullable=False, comment='所属图表ID'),
    sa.Column('source_node_id', sa.Integer(), nullable=False, comment='源节点ID'),
    sa.Column('target_node_id', sa.Integer(), nullable=False, comment='目标节点ID'),
    sa.Column('interface_type', sa.String(length=100), nullable=True, comment='接口类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='接口描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['diagram_id'], ['n_squared_diagrams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['n_squared_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['n_squared_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='N-squared边表'
    )
    op.create_index('idx_nsq_edge_diagram', 'n_squared_edges', ['diagram_id'], unique=False)
    op.create_index('idx_nsq_edge_source', 'n_squared_edges', ['source_node_id'], unique=False)
    op.create_index('idx_nsq_edge_target', 'n_squared_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nsq_edge_target', table_name='n_squared_edges')
    op.drop_index('idx_nsq_edge_source', table_name='n_squared_edges')
    op.drop_index('idx_nsq_edge_diagram', table_name='n_squared_edges')
    op.drop_table('n_squared_edges')
    op.drop_index('idx_sim_result_design', table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index('idx_nsq_node_id', table_name='n_squared_nodes')
    op.drop_index('idx_nsq_node_diagram', table_name='n_squared_nodes')
    op.drop_table('n_squared_nodes')
    op.drop_index('idx_model_version', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('idx_dvm_variable', table_name='dvm_matrix')
    op.drop_index('idx_dvm_project', table_name='dvm_matrix')
    op.drop_index('idx_dvm_attribute', table_name='dvm_matrix')
    op.drop_table('dvm_matrix')
    op.drop_table('value_attributes')
    op.drop_table('user_models')
    op.drop_index('idx_sensitivity_project', table_name='sensitivity_analyses')
    op.drop_table('sensitivity_analyses')
    op.drop_table('project_states')
    op.drop_index('idx_pareto_project', table_name='pareto_analyses')
    op.drop_table('pareto_analyses')
    op.drop_table('n_squared_diagrams')
    op.drop_table('missions')
    op.drop_index('idx_mcdm_project', table_name='mcdm_analyses')
    op.drop_table('mcdm_analyses')
    op.drop_table('design_variables')
    op.drop_index('idx_design_alt_project', table_name='design_alternatives')
    op.drop_table('design_alternatives')
    op.drop_table('projects')
    # ### end Alembic commands ###
